services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - service=user
    ports:
      - "4001:4001"
    env_file:
      - ./services/user/.env
    networks:
      - wellness-roots-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - service=auth
    ports:
      - "4003:4003"
    env_file:
      - ./services/auth/.env
    networks:
      - wellness-roots-network

  email-service:
    container_name: email-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - service=email
    ports:
      - "4004:4004"
    env_file:
      - ./services/email/.env
    networks:
      - wellness-roots-network

  review-service:
    container_name: review-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - service=review
    ports:
      - "4005:4005"
    env_file:
      - ./services/review/.env
    networks:
      - wellness-roots-network

  orchestrator-service:
    container_name: orchestrator-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - service=orchestrator
    ports:
      - "4007:4007"
    env_file:
      - ./services/orchestrator/.env
    networks:
      - wellness-roots-network

networks:
  wellness-roots-network:
    driver: bridge