---
# Notification Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: menushaeshan/notification:tag
          ports:
          - containerPort: 4009
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: LoadBalancer
  ports:
  - port: 4009
  selector:
    app: notification
---
# Review Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: menushaeshan/review:tag
          ports:
          - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  type: LoadBalancer
  ports:
  - port: 4005
  selector:
    app: review
---
# Seller Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller
  template:
    metadata:
      labels:
        app: seller
    spec:
      containers:
        - name: seller
          image: menushaeshan/seller:tag
          ports:
          - containerPort: 4006
---
apiVersion: v1
kind: Service
metadata:
  name: seller
spec:
  type: LoadBalancer
  ports:
  - port: 4006
  selector:
    app: seller
---
# Payment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: menushaeshan/payment:tag
          ports:
          - containerPort: 4020
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: LoadBalancer
  ports:
  - port: 4020
  selector:
    app: payment
---
# Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: menushaeshan/order:tag
          ports:
          - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: LoadBalancer
  ports:
  - port: 4002
  selector:
    app: order
---
# User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: menushaeshan/user:tag
          ports:
          - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: LoadBalancer
  ports:
  - port: 4001
  selector:
    app: user
---
# Delivery Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: menushaeshan/delivery:tag
          ports:
          - containerPort: 4008
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
spec:
  type: LoadBalancer
  ports:
  - port: 4008
  selector:
    app: delivery
---
# Orchestrator Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: menushaeshan/orchestrator:tag
          ports:
          - containerPort: 4007
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  type: LoadBalancer
  ports:
  - port: 4007
  selector:
    app: orchestrator
---
# Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: menushaeshan/auth:tag
          ports:
          - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: LoadBalancer
  ports:
  - port: 4003
  selector:
    app: auth
---
# Email Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: menushaeshan/email:tag
          ports:
          - containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  type: LoadBalancer
  ports:
  - port: 4004
  selector:
    app: email
