# Payment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: menushaeshan/payment:tag
          imagePullPolicy: Always
          ports:
          - containerPort: 4020
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: DB_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 4020
  selector:
    app: payment-service
