# Review Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: menushaeshan/review:tag
          imagePullPolicy: Always
          ports:
          - containerPort: 4005
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: review-service-secrets
                  key: DB_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: review-service-secrets
                  key: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: ClusterIP
  ports:
  - port: 4005
  selector:
    app: review-service
