name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [review, delivery, order, seller, payment, notification, auth, user, email, orchestrator]    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install Dependencies
      run: pnpm install
    - name: Run Tests
      run: pnpm test
    - name: Build
      run: pnpm run build

    - name: Build Docker image
      run: docker build --build-arg service=${{ matrix.service }} -t assessment2_devops-${{ matrix.service }}-service:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Tag and push Docker image
      run: |
        docker tag assessment2_devops-${{ matrix.service }}:latest ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:tag
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:tag
